# Generated by Django 6.0.2 on 2026-02-09 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Family House', 'Family House'), ('Bachelor House', 'Bachelor House')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('size_sqft', models.PositiveIntegerField()),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('main_image', models.ImageField(upload_to='property_images/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.city')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('subarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='locations.subarea')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
