# Generated by Django 6.0.2 on 2026-02-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='size_sqft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
