# Generated by Django 6.0.2 on 2026-02-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_contact_name_property_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='contact_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
