# Generated by Django 6.0.2 on 2026-02-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_dog_allowed_property_garage_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
