# Generated by Django 6.0.2 on 2026-03-27 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('properties', '0009_alter_property_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='size_sqft',
            field=models.PositiveIntegerField(blank=True, help_text='Size in square feet', null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties__city_id_6c1ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['area'], name='properties__area_id_a3c123_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties__propert_5c7790_idx'),
        ),
    ]
